name: Benchmark

on:
  workflow_dispatch:

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Fetch all history for comparison

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"

      - name: Install protoc and protoc-gen-go
        run: |
          sudo apt-get update -y
          sudo apt-get install -y protobuf-compiler
          sudo apt-get install -y protoc-gen-go

      - name: Download dependencies
        run: go mod download

      - name: Generate protobuf code
        run: make proto

      - name: Run benchmarks
        run: |
          go test -bench=. -benchmem -benchtime=3s | tee benchmark.txt

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: benchmark.txt

      - name: Display results
        run: cat benchmark.txt
